<#
.SYNOPSIS
    Produces the Azure AD Assessment recommendations for Email One Time PassCode.
.DESCRIPTION
    This cmdlet generates the recommendations from email OTP configuration.
    Enabling Email OTP allows guest users to redeem with their mail address and prevents consequent complications generated by the usage of Viral AAD accounts or MSA accounts.
.EXAMPLE
    PS C:\> Get-EOTPRecommendation -Path "C:\AzureADAssessment\AzureADAssessment-contoso.onmicrosoft.com"
    Reads Email OTP configuration from "C:\AzureADAssessment\AzureADAssessment-contoso.onmicrosoft.com" and generate recommendation.
#>
function Get-EOTPRecommendation {
    [CmdletBinding()]
    param (
        # Specifies a path where extracted data resides (folder)
        [Parameter(Mandatory = $true, Position = 0, ValueFromPipeline = $true)]
        [string] $Path
    )

    #Start-AppInsightsRequest $MyInvocation.MyCommand.Name

    ### Prepare paths
    $AssessmentDetailPath = Join-Path $Path "AzureADAssessment.json"

    ### Read assessment data
    $AssessmentDetail = Get-Content $AssessmentDetailPath -Raw | ConvertFrom-Json

    ### Generate AAD data path
    $AADPath = Join-Path $Path "AAD-$($AssessmentDetail.AssessmentTenantDomain)"

    ### Get the configuration from file
    $eotpconfig = get-content -Path (Join-Path $AADPath "emailOTPMethodPolicy.json") | ConvertFrom-Json

    if ($eotpconfig.state -ne "enabled" -or $eotpconfig.allowExternalIdToUseEmailOtp -ne "enabled") {
        ### Generate recommendation
        $rec = "" | select-object Category,Area,Name,Summary,Recommendation,Priority,DataReport
        $rec.Category = "Access Management"
        $rec.Area = "Authentication Experience"
        $rec.Name = "Email OTP"
        $rec.Summary = "With email OTP, org members can collaborate with anyone in the world by simply sharing a link or sending an invitation via email. Invited users prove their identity by using a verification code sent to their email account"
        $rec.Recommendation = "Enable email OTP"
        $rec.Priority = "P2"
        $rec.DataReport = @(Join-Path $AADPath "emailOTPMethodPolicy.json")
        $rec
    }

    #Complete-AppInsightsRequest $MyInvocation.MyCommand.Name -Success $?
}